version: '3.4'

services:
  lagersolutionDb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    container_name: dbcontainer
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
  lagertestproject:
    image: ${DOCKER_REGISTRY-}lagertestproject
    build:
      context: .
      dockerfile: LagerTestProject/Dockerfile
